# Generated by Django 4.2.16 on 2025-07-06 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("billing", "Rechnungsadresse"),
                            ("shipping", "Lieferadresse"),
                            ("work", "Arbeitsadresse"),
                            ("home", "Privatadresse"),
                        ],
                        default="billing",
                        max_length=20,
                    ),
                ),
                ("street", models.CharField(max_length=255)),
                ("street_number", models.CharField(max_length=20)),
                ("postal_code", models.CharField(max_length=10)),
                ("city", models.CharField(max_length=100)),
                ("country", models.CharField(default="Deutschland", max_length=50)),
                (
                    "address_line_2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "verbose_name": "Adresse",
                "verbose_name_plural": "Adressen",
            },
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("legal_form", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "trade_register_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("tax_number", models.CharField(blank=True, max_length=50, null=True)),
                ("vat_number", models.CharField(blank=True, max_length=50, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                ("fax", models.CharField(blank=True, max_length=50, null=True)),
                ("website", models.URLField(blank=True, null=True)),
                ("bank_name", models.CharField(blank=True, max_length=100, null=True)),
                ("iban", models.CharField(blank=True, max_length=34, null=True)),
                ("bic", models.CharField(blank=True, max_length=11, null=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="company_logos/"
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("is_own_company", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Firma",
                "verbose_name_plural": "Firmen",
            },
        ),
        migrations.CreateModel(
            name="ContactPerson",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "salutation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("herr", "Herr"),
                            ("frau", "Frau"),
                            ("firma", "Firma"),
                        ],
                        max_length=10,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("title", models.CharField(blank=True, max_length=50, null=True)),
                ("position", models.CharField(blank=True, max_length=100, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                ("mobile", models.CharField(blank=True, max_length=50, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("is_primary", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Ansprechpartner",
                "verbose_name_plural": "Ansprechpartner",
            },
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                (
                    "note_type",
                    models.CharField(
                        choices=[
                            ("general", "Allgemein"),
                            ("phone", "Telefonat"),
                            ("email", "E-Mail"),
                            ("meeting", "Termin"),
                            ("internal", "Intern"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                ("object_id", models.CharField(max_length=100)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notiz",
                "verbose_name_plural": "Notizen",
                "ordering": ["-created_at"],
            },
        ),
    ]
