# Generated by Django 4.2.16 on 2025-07-06 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("employee_number", models.CharField(max_length=20, unique=True)),
                (
                    "employment_status",
                    models.CharField(
                        choices=[
                            ("active", "Aktiv"),
                            ("inactive", "Inaktiv"),
                            ("vacation", "Urlaub"),
                            ("sick", "Krank"),
                            ("terminated", "Gekündigt"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("full_time", "Vollzeit"),
                            ("part_time", "Teilzeit"),
                            ("apprentice", "Auszubildender"),
                            ("freelancer", "Freiberufler"),
                            ("temporary", "Zeitarbeit"),
                        ],
                        default="full_time",
                        max_length=20,
                    ),
                ),
                ("birth_date", models.DateField(blank=True, null=True)),
                (
                    "phone_private",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "phone_business",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("mobile", models.CharField(blank=True, max_length=50, null=True)),
                ("department", models.CharField(blank=True, max_length=100, null=True)),
                ("position", models.CharField(blank=True, max_length=100, null=True)),
                ("hire_date", models.DateField()),
                ("termination_date", models.DateField(blank=True, null=True)),
                (
                    "weekly_hours",
                    models.DecimalField(decimal_places=2, default=40.0, max_digits=5),
                ),
                (
                    "hourly_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("qualifications", models.TextField(blank=True, null=True)),
                ("certifications", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "emergency_contact_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.address",
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subordinates",
                        to="employees.employee",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Mitarbeiter",
                "verbose_name_plural": "Mitarbeiter",
                "ordering": ["employee_number"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeDocument",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("contract", "Arbeitsvertrag"),
                            ("id_copy", "Ausweiskopie"),
                            ("certificate", "Zertifikat"),
                            ("reference", "Zeugnis"),
                            ("medical", "Gesundheitszeugnis"),
                            ("training", "Schulungsnachweis"),
                            ("other", "Sonstiges"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("file", models.FileField(upload_to="employees/documents/")),
                ("description", models.TextField(blank=True, null=True)),
                ("issue_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("file_size", models.IntegerField(blank=True, null=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="employees.employee",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Mitarbeiterdokument",
                "verbose_name_plural": "Mitarbeiterdokumente",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeAvailability",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "availability_type",
                    models.CharField(
                        choices=[
                            ("vacation", "Urlaub"),
                            ("sick_leave", "Krankheit"),
                            ("training", "Schulung"),
                            ("business_trip", "Dienstreise"),
                            ("unavailable", "Nicht verfügbar"),
                            ("available", "Verfügbar"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("reason", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("is_approved", models.BooleanField(default=False)),
                ("approved_date", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_availabilities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availabilities",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mitarbeiterverfügbarkeit",
                "verbose_name_plural": "Mitarbeiterverfügbarkeiten",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeSkill",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("technical", "Technische Fähigkeiten"),
                            ("certification", "Zertifizierungen"),
                            ("language", "Sprachen"),
                            ("software", "Software-Kenntnisse"),
                            ("safety", "Sicherheit"),
                            ("other", "Sonstiges"),
                        ],
                        default="technical",
                        max_length=20,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("beginner", "Anfänger"),
                            ("intermediate", "Fortgeschritten"),
                            ("advanced", "Experte"),
                            ("expert", "Spezialist"),
                        ],
                        default="intermediate",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("acquired_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                (
                    "certification_body",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "certificate_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mitarbeiterfähigkeit",
                "verbose_name_plural": "Mitarbeiterfähigkeiten",
                "unique_together": {("employee", "name", "category")},
            },
        ),
    ]
