# Generated by Django 4.2.16 on 2025-07-06 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "appointment_type",
                    models.CharField(
                        choices=[
                            ("consultation", "Beratung"),
                            ("site_visit", "Vor-Ort-Besichtigung"),
                            ("installation", "Installation"),
                            ("maintenance", "Wartung"),
                            ("repair", "Reparatur"),
                            ("meeting", "Besprechung"),
                            ("phone_call", "Telefonat"),
                            ("other", "Sonstiges"),
                        ],
                        default="consultation",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Geplant"),
                            ("confirmed", "Bestätigt"),
                            ("in_progress", "In Bearbeitung"),
                            ("completed", "Abgeschlossen"),
                            ("cancelled", "Abgesagt"),
                            ("no_show", "Nicht erschienen"),
                            ("rescheduled", "Verschoben"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Niedrig"),
                            ("medium", "Mittel"),
                            ("high", "Hoch"),
                            ("urgent", "Dringend"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("start_datetime", models.DateTimeField()),
                ("end_datetime", models.DateTimeField()),
                (
                    "duration_hours",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                ("location", models.TextField(blank=True, null=True)),
                ("reminder_sent", models.BooleanField(default=False)),
                ("reminder_datetime", models.DateTimeField(blank=True, null=True)),
                ("internal_notes", models.TextField(blank=True, null=True)),
                ("customer_notes", models.TextField(blank=True, null=True)),
                (
                    "travel_time_to",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
                ),
                (
                    "travel_time_from",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
                ),
                (
                    "assigned_employees",
                    models.ManyToManyField(
                        blank=True,
                        related_name="assigned_appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="customers.customer",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="appointments",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Termin",
                "verbose_name_plural": "Termine",
                "ordering": ["start_datetime"],
            },
        ),
        migrations.CreateModel(
            name="Calendar",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "calendar_type",
                    models.CharField(
                        choices=[
                            ("personal", "Persönlich"),
                            ("team", "Team"),
                            ("company", "Firma"),
                            ("customer", "Kunde"),
                            ("project", "Projekt"),
                        ],
                        default="personal",
                        max_length=20,
                    ),
                ),
                ("color", models.CharField(default="#007bff", max_length=7)),
                ("is_active", models.BooleanField(default=True)),
                ("is_public", models.BooleanField(default=False)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_calendars",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Kalender",
                "verbose_name_plural": "Kalender",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RecurringAppointment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "appointment_type",
                    models.CharField(
                        choices=[
                            ("consultation", "Beratung"),
                            ("site_visit", "Vor-Ort-Besichtigung"),
                            ("installation", "Installation"),
                            ("maintenance", "Wartung"),
                            ("repair", "Reparatur"),
                            ("meeting", "Besprechung"),
                            ("phone_call", "Telefonat"),
                            ("other", "Sonstiges"),
                        ],
                        default="consultation",
                        max_length=20,
                    ),
                ),
                (
                    "recurrence_type",
                    models.CharField(
                        choices=[
                            ("daily", "Täglich"),
                            ("weekly", "Wöchentlich"),
                            ("monthly", "Monatlich"),
                            ("yearly", "Jährlich"),
                        ],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                ("interval", models.IntegerField(default=1)),
                ("start_time", models.TimeField()),
                (
                    "duration_hours",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=4),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("location", models.TextField(blank=True, null=True)),
                ("internal_notes", models.TextField(blank=True, null=True)),
                (
                    "assigned_employees",
                    models.ManyToManyField(
                        blank=True,
                        related_name="assigned_recurring_appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_recurring_appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurring_appointments",
                        to="customers.customer",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recurring_appointments",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wiederkehrender Termin",
                "verbose_name_plural": "Wiederkehrende Termine",
                "ordering": ["start_date"],
            },
        ),
        migrations.CreateModel(
            name="CalendarPermission",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "permission_level",
                    models.CharField(
                        choices=[
                            ("view", "Anzeigen"),
                            ("edit", "Bearbeiten"),
                            ("admin", "Verwalten"),
                        ],
                        default="view",
                        max_length=20,
                    ),
                ),
                (
                    "calendar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schedules.calendar",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Kalender-Berechtigung",
                "verbose_name_plural": "Kalender-Berechtigungen",
                "unique_together": {("calendar", "user")},
            },
        ),
        migrations.AddField(
            model_name="calendar",
            name="shared_with",
            field=models.ManyToManyField(
                related_name="shared_calendars",
                through="schedules.CalendarPermission",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="AppointmentNote",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("is_internal", models.BooleanField(default=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="schedules.appointment",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Terminnotiz",
                "verbose_name_plural": "Terminnotizen",
                "ordering": ["-created_at"],
            },
        ),
    ]
