# Generated by Django 4.2.16 on 2025-07-06 19:12

import datetime
from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("invoice_number", models.CharField(max_length=20, unique=True)),
                (
                    "invoice_type",
                    models.CharField(
                        choices=[
                            ("invoice", "Rechnung"),
                            ("credit_note", "Gutschrift"),
                            ("reminder", "Mahnung"),
                            ("final_reminder", "Letzte Mahnung"),
                        ],
                        default="invoice",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Entwurf"),
                            ("sent", "Versendet"),
                            ("paid", "Bezahlt"),
                            ("overdue", "Überfällig"),
                            ("cancelled", "Storniert"),
                            ("refunded", "Erstattet"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("invoice_date", models.DateField(default=datetime.date.today)),
                ("due_date", models.DateField()),
                ("payment_date", models.DateField(blank=True, null=True)),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("19.00"), max_digits=5
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "discount_percent",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("payment_terms", models.TextField(blank=True, null=True)),
                ("internal_notes", models.TextField(blank=True, null=True)),
                (
                    "payment_reference",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="customers.customer",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rechnung",
                "verbose_name_plural": "Rechnungen",
                "ordering": ["-invoice_date", "-invoice_number"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("payment_date", models.DateField(default=datetime.date.today)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("bank_transfer", "Überweisung"),
                            ("cash", "Bargeld"),
                            ("card", "Kartenzahlung"),
                            ("check", "Scheck"),
                            ("direct_debit", "Lastschrift"),
                            ("other", "Sonstiges"),
                        ],
                        default="bank_transfer",
                        max_length=20,
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "bank_reference",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="invoices.invoice",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Zahlung",
                "verbose_name_plural": "Zahlungen",
                "ordering": ["-payment_date"],
            },
        ),
        migrations.CreateModel(
            name="Reminder",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reminder_level",
                    models.IntegerField(
                        choices=[
                            (1, "1. Mahnung"),
                            (2, "2. Mahnung"),
                            (3, "3. Mahnung (Letzte Mahnung)"),
                        ]
                    ),
                ),
                ("reminder_date", models.DateField(default=datetime.date.today)),
                (
                    "reminder_fee",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("is_sent", models.BooleanField(default=False)),
                ("sent_date", models.DateField(blank=True, null=True)),
                ("reminder_text", models.TextField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="invoices.invoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mahnung",
                "verbose_name_plural": "Mahnungen",
                "ordering": ["-reminder_date", "-reminder_level"],
                "unique_together": {("invoice", "reminder_level")},
            },
        ),
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("position_number", models.IntegerField()),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("material", "Material"),
                            ("service", "Dienstleistung"),
                            ("labor", "Arbeitszeit"),
                            ("discount", "Rabatt"),
                            ("text", "Textposition"),
                        ],
                        default="material",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("1.00"), max_digits=10
                    ),
                ),
                ("unit", models.CharField(default="Stück", max_length=20)),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("item_number", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "discount_percent",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="invoices.invoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rechnungsposition",
                "verbose_name_plural": "Rechnungspositionen",
                "ordering": ["position_number"],
                "unique_together": {("invoice", "position_number")},
            },
        ),
    ]
